.github/workflows/lychee-push.yml
Currently, the GH workflow is not triggered when a PR is made from a fork. Example: https://github.com/signalfx/gdi-specification/pull/85
Run when:
- pushed/merged to `main`
- PR is created/updated
- someone manually triggers a build: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
=> Change lychee-push GitHub workflow triggers

specification/repository.md
It may be helpful if the default permissions of the GITHUB_TOKEN are not set on the organization level.
Require setting the repository's default permissions of the GITHUB_TOKEN.
This change only makes sense if it is not already set on the organization level.
It can also help with "controlled" adoption of using only required permissions  of the GITHUB_TOKEN instead of doing a "big bang"
=> Repository's default permissions of the GITHUB_TOKEN

.github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/ga_request.md, README.md, specification/configuration.md, specification/repository.md, specification/templates/CHANGELOG.md, specification/templates/CONTRIBUTING.md, specification/versioning.md
Solves https://github.com/signalfx/gdi-specification/issues/100
1. There is something like GitHub Project which is something else than a GitHub Repository
1. A common definition for the project is "a temporary endeavor undertaken to create a unique result"
Use the term `repository` instead of `project` in most places.
=> Change wording "project" to "repository" where appropriate

CHANGELOG.md, specification/templates/CHANGELOG.md
- First stable release of the GDI specification. This release includes stable requirements and recommendations for GDI repository composition and versioning and Splunk distributions of OpenTelemetry configuration.
=> Release 1.0.0

specification/templates/.github/CODEOWNERS
As discussed in Slack, this PR aims at standardizing docs team as reviewers for all changes concerning documentation in our repos.
=> Update CODEOWNERS to add docs team as reviewers for docs changes

specification/repository.md
Resolves https://github.com/signalfx/gdi-specification/issues/118
I included all teams specified in the CODEOWNERS template.
=> Grant WRITE permission to signalfx/docs team (for code reviews)

CHANGELOG.md, specification/configuration.md
These lines are empty of meaning as this specification is not intending users to be the audience. Furthermore, there is no specified action to take for the instrumentation authors if values are not provided.
=> Remove lines on what configuration a user should provide

specification/configuration.md
While majority of the SignalFx tracing libraries set this limit to `1200`, it turns out the actual intended value was `12000` as done by SignalFx Java.
=> Max attr length fix

specification/repository.md, specification/templates/CONTRIBUTING.md
This PR adds a note to our `CONTRIBUTING.md` template to clarify that prescriptive guidance is hosted on https://docs.splunk.com/Observability and how can contributors send feedback about it.
=> Introduce docs section to CONTRIBUTING.md

README.md, specification/configuration.md, specification/profiling.md, specification/repository.md, specification/versioning.md
In many places, the term component was used in place of GDI repository.
=> Ensure component is used properly

CHANGELOG.md, specification/configuration.md
Some systems, Android, cannot enforce this configuration value at the library level. It needs to be enforced at the application level. Therefore, this part of the specification is unimplementable by the Android RUM library. This adds an exception to this requirement to allow the Android RUM library to be compliant.
=> Clarify RUM beaconEndpoint value enforcement

specification/configuration.md
Also add language around Splunk Observability versus Platform
=> Add data collection configuration for Kubernetes

specification/configuration.md
`splunkPlatform.metricsEnabled` is `false` by default because there is no default metrics type index unless user creates it. User need to specify `splunkPlatform.metricsIndex` after creating the index.
=> Update Kubernetes Configuration for Splunk Platform

CHANGELOG.md, specification/configuration.md
Changed the example for Java properties to env vars (it referred to a deprecated varname).
=> Fix Java System properties example

specification/semantic_conventions.md
1. Added different statuses per semantic conventions section - everything but RUM is stable, RUM is feature-freeze (same as in the configuration doc)
2. Changed `os.type` to `os.name` - I think it was a bug previously, since both [otel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/os.md) and [Android RUM](https://github.com/signalfx/splunk-otel-android/blob/main/splunk-otel-android/src/main/java/com/splunk/rum/RumAttributeAppender.java#L68) actually use `os.name`
=> Minor fixes in RUM spec

specification/profiling.md
Some small things found when reviewing recently:
* Added link to upstream logs
* Fix casing on MUST
* link to logs protobuf
* Add 2 additional format lines to show examples with <col>
=> profiling: a few small tweaks

specification/configuration.md
=> Add `SPLUNK_REALM` to instrumentation library configuration

specification/semantic_conventions.md
Allocation profiling uses the same log records as call stack sampling.
=> Add memory allocation size attribute

specification/semantic_conventions.md
For node.js and for some JFR events, thread metadata details are unavailable. Because of this, we don't really want to force an artificial metadata line to be created, so we relax this and allow the entire line to be empty if no metadata is known.
=> Allow thread metadata line to be empty

specification/configuration.md
Serverless config spec change:
- defaults to OTLP over HTTP (as supported by direct ingest)
- don't require JT exporter (increases package size for eg Java)
=> serverless spec change

specification/semantic_conventions.md
`name` field was removed from log data model, see https://github.com/open-telemetry/opentelemetry-specification/pull/2271
=> Remove Name from the required profiling LogRecord fields

specification/semantic_conventions.md
Describe sending profiling data in [pprof](https://github.com/google/pprof) [profile.proto](https://github.com/google/pprof/tree/master/proto) format. Pprof payload will contain a batch of samples. Attributes describing an individual sample, that in currently used `text` format are added to `LogRecord`, are added as label to pprof sample.
@vovencij @gsmirnov-splk please review
=> profiling: pprof profile.proto format

specification/semantic_conventions.md
@vovencij @gsmirnov-splk please review
Add an attribute for marking truncated stack traces so that profiling backend would know that the stack trace has missing frames.
=> profiling: add attribute for truncated stack trace

specification/semantic_conventions.md
Based on https://github.com/signalfx/signalfx-dotnet-tracing/pull/565
Make the documentation more specific for the attributes needed for pprof/text format.
Changes should not affect existing implementation (like Java).
=> Pprof related fixes

specification/semantic_conventions.md
The unit for `source.event.period` wasn't specified, however agents send it in milliseconds. But what if we ever want to use sub millisecond intervals? :eyes:
=> chore: clarify source.event.period unit

specification/repository.md
This is more in keeping with the github terminology.
=> Change "primary" to "default" for branch name.

specification/configuration.md
The configs have not change in 9 months and we are not aware of any pressing/short-term additions to the core configuration.
=> Mark RUM configuration items as stable.

specification/configuration.md
For now, splunk-otel-java is using
for CPU profiling
- `splunk.profiler.enabled` - command switch
- `SPLUNK_PROFILER_ENABLED` - env. var.
for memory profiling only command switch `splunk.profiler.memory.enabled`.
SignalFx for .NET is using only `SIGNALFX_PROFILER_ENABLED` for CPU profiling.
splunk-otel-js using only `SPLUNK_PROFILER_ENABLED` for CPU profiling.
We are in progress of adding memory profiling do SFx for .NET. It will be good to introduce common way to enable it (with different prefix).
Additional tasks:
- for splunk-otel-java - add support to new env. variable
- SFx for .NET - start using new env. when needed
- splunk-otel-js - start using new env. when needed
=> add SPLUNK_PROFILER_MEMORY_ENABLED

specification/configuration.md
I think the current description is a little confusing.
Also see: https://github.com/signalfx/splunk-otel-ruby/issues/46#issuecomment-1234778117
=> Reduce confusion in Span Collection Limits config

specification/repository.md
Reverts signalfx/gdi-specification#186
This does not look to have had consensus across implementations.
_Based on comment originally posted by @breedx-splk in https://github.com/signalfx/gdi-specification/issues/186#issuecomment-1234431840_
=> Revert "MUST NOT use GitHub secrets"

specification/repository.md
Per internal agreement.
Practice "defense in depth".
Add a requirement to use https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules to increase the protection of our release train.
=> Add tag protection requirement

README.md, repositories.txt
Towards https://github.com/signalfx/gdi-specification/issues/63
Add a list of GDI repositories to be clear for what repositories the spec should be applied. 
It should also facilitate the releasing process. We could create issues in the GDI repos when a new version of the spec is released.
=> Add a list of GDI repositories

specification/configuration.md
Fixes https://github.com/signalfx/gdi-specification/issues/194
The `SPLUNK_METRICS_ENDPOINT` is either not a stable setting or it is not supported in any of the existing instrumentation libraries.
1. In https://github.com/signalfx/splunk-otel-java it is marked as "experimental"
2. In https://github.com/signalfx/splunk-otel-js it looks like a undocumented functionality (so even less than "experimental")
3. https://github.com/signalfx/splunk-otel-go logs that it is not supported if it is set
Initially I wanted to add a "note" that this env var is not required, but a lean towards removing it from the spec. We should use/follow OTel metrics.
Also, during GDI spec review, none of the @signalfx/gdi-specification-maintainers was considering this env var as MUST HAVE.
At last, we do not want to …
=> Remove SPLUNK_METRICS_ENDPOINT from Instrumentation Libraries

specification/configuration.md
The OTel specification has been updated some time ago: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specify-protocol
Now, `http/protobuf` is the recommended default transport protocol. 
Also for technical reasons, in .NET our distro, we do not want to default to gRPC protocol. More [here](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/main/docs/config.md#otlp)
Our backend accepts OTLP over `http/protobuf` on: `https://ingest/.{REALM}.signalfx.com/v2/trace/otlp`
1. Allow defaulting to `http/protobuf`.
2. Remove the default value as this is the same on as [specified in Otel](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md)
This change is …
=> Update OTLP exporter default requirements

specification/repository.md
1. Root cause: https://github.com/signalfx/gdi-specification/pull/192#issuecomment-1324756625
2. Maintainers should be able to configure the repository so that it complies to the GDI spec (e.g. setup branch protection rules)
3. Maintainers  should be able to remove tags and update branch protection rules when necessary
4. There is no definition what an "admin team" is. Currently we have only an admin team for instrumentation repositories.
5. The maintainers is supposed to contain a limited number of contributors 
- Grant `Admin` role for `-maintainers` team
- Remove the line about the "admin team"
=> Grant Admin role for maintainers team

specification/repository.md
Introduced in #50 .
I do not see any benefits as we do not use any JIRA-GitHub integration.
=> Drop Jira app requirement

specification/semantic_conventions.md
Redundant and also conflicting. It's already defaulted to `unknown` and `0` in field list above.
=> Remove redunant statement about file and line

specification/semantic_conventions.md
Maintenance 😉  These resource attributes are already set by our distributions.
Add a recommendation to set process resource attributes.
=> Add a recommendation to set process resource attributes

specification/semantic_conventions.md
Maintenance 😉 AFAIK the runtime metrics instrumentation is already in all our distributions.
Add a recommendation to set process resource attributes.
I do not want to make it as `MUST` because the lack of it should not block a distro release. 
I do not want to to make it as `Stable` because it is not stable in the OTel spec.
=> Add a recommendation to collect Runtime Environment Metrics

specification/semantic_conventions.md
Profiling team requests that `pprof` messages should be accompanied by the number of stack frames (non-unique) represented in the `pprof`.
@gsmirnov-splk please review
=> Add frame count to pprof message attributes

.github/ISSUE_TEMPLATE/ga_request.md, .github/workflows/ci.yml, CHANGELOG.md, RELEASING.md
- Remove `SPLUNK_METRICS_ENDPOINT` from Instrumentation Libraries
(it was never really stable).
- Add `SPLUNK_PROFILER_MEMORY_ENABLED`.
- Deprecate `jaeger-thrift-splunk` option for `OTEL_TRACES_EXPORTER`.
- Remove the policy regarding Zipkin exporter.
- OTLP exporter can use either `grpc` or `http/protobuf`
as the default transport protocol.
- Add tag protection rule requirement.
- Add Dependabot security configuration requirements.
- Grant Admin role for maintainers team.
- Allow using the documentation public repository
and reference it in the `CONTRIBUTING.md` template.
- Require documenting all configuration parameters
that are relevant to Splunk Observability Cloud.
- Require documenting all configuration parameters
whose default or accepted values deviate from upstream.
- Remove …
=> Release 1.5.0

specification/repository.md
This adds a proposal for labeling changes in the CHANGELOG.md file so as to better distinguish which are coming from upstream as opposed to our repos.
Example: https://github.com/signalfx/splunk-otel-collector/blob/main/CHANGELOG.md
=> Add labels proposal to changelog requirements

specification/configuration.md
Based on previous wording we have made it unset in .NET (defaulting OTel values) for all other variables.
Ref links:
* .NET https://github.com/signalfx/splunk-otel-dotnet/blob/f9146737017242c8d74572feec719b1e8f9baa58/src/Splunk.OpenTelemetry.AutoInstrumentation/SdkLimitOptionsConfigurator.cs#L29-L40
* Java https://github.com/signalfx/splunk-otel-dotnet/blob/f9146737017242c8d74572feec719b1e8f9baa58/test/Splunk.OpenTelemetry.AutoInstrumentation.Tests/SdkLimitOptionsConfiguratorTests.cs#L21
* Go-lang https://github.com/signalfx/splunk-otel-go/blob/b78a37105554d81d0cbb4b793aff8c448f1e776f/distro/limits.go#L62
=> Change wording for span connection limits

specification/configuration.md, specification/repository.md, specification/templates/.github/CODEOWNERS
Several things that I think need to be updated before we can sign off on #248
=> Update repository permissions and log message when service name is not set

specification/repository.md
Blocker for https://github.com/signalfx/gdi-specification/issues/254
The current repository permissions does not make sense for repos such us https://github.com/signalfx/splunk-otel-collector, https://github.com/signalfx/splunk-otel-collector-operator, https://github.com/signalfx/splunk-otel-collector-chart, https://github.com/signalfx/splunk-otel-collector-heroku
=> Fix permissions to be applicable for non-instrumentation repositories

.github/workflows/ci.yml, CHANGELOG.md
- Update the log message when `service.name` resource attribute is not set.
- Update `CONTRIBUTING.md` template to require signing commits.
- Suggest changelog sub-sections and labels.
- Require releases to contain a link to the upstream release notes.
- Add repiository permission exception for bot accounts.
- Remove `signalfx/gdi-specification-*` teams from permissions.
- Add admins team.
=> Release 1.6.0

.github/workflows/cla.yaml
Towards https://github.com/signalfx/gdi-specification/issues/236
Add CLA Assistant GitHub workflow to this repository.
Testing here: https://github.com/pellared/test-cla/pull/1 as I do NOT want to change the default branch in this repository for sake of testing.
Test passed: https://github.com/splunk/cla-agreement/commit/28bce313e329c76f03f92fc0d2f358a3dcf113d8
Next steps
1. Add a requirement to have a CLA GitHub workflow here: https://github.com/signalfx/gdi-specification/blob/add-cla/specification/repository.md#github-actions
2. Add CLA GitHub workflow to other repositories.
=> Add CLA Assistant GitHub workflow

.github/workflows/cla.yml
Add missing permissions.
I read https://github.com/contributor-assistant/github-action source code and it needs `write` on `actions` (see [here](https://github.com/contributor-assistant/github-action/blob/a895a435fcce79ecf28fbce61a4ef0f0dabc9853/src/pullRerunRunner.ts#L21-L24)) and `write` on `statuses`  (see [here](https://github.com/contributor-assistant/github-action/blob/a895a435fcce79ecf28fbce61a4ef0f0dabc9853/src/pullrequest/signatureComment.ts#L43-L45)).
`write` on `contents` should not be needed when signatures are stored in a remote repository.
PS. I created https://github.com/contributor-assistant/github-action/pull/144
=> Update cla.yml permissions

CHANGELOG.md, specification/repository.md
The otel upstream repos for java and android are using Renovatebot. It as a few advantages, including combined PRs and maintenenance of a summary issue for dependencies. I'd like to switch over to it in our splunk java GDI repos as well.
=> Add renovatebot as a dependency management option

CHANGELOG.md, specification/templates/CONTRIBUTING.md
Per https://github.com/signalfx/splunk-otel-android/pull/659#discussion_r1360891483
=> Update CLA notice in CONTRIBUTING.md

CHANGELOG.md, specification/configuration.md
Currently iOS and android have different config options for enabling and configuring disk buffering.
Android
enableDiskBuffering
limitDiskUsageMegabytes
iOS
enableDiskCache
spanDiskCacheMaxSize
Also react native needs to use the same conf. After discussions it seems "buffering" makes more sense so let's use android version. Not sure where to put mobile only conf options put them into the same table.
=> Add disk buffering config options to RUM conf

CHANGELOG.md, specification/semantic_conventions.md
Fixes #267.
Adjust our requirements to https://github.com/open-telemetry/semantic-conventions/pull/178
- Deprecate `splunk.distro.version`, - As it can be replaced by `telemetry.auto.version` and `telemetry.distro.name`. 
- Change `telemetry.auto.version` to `telemetry.distro.version`, - technically not a breaking change, as it was marked as SHOULD
- Add `telemetry.distro.name` resource attribute. - new attribute, not breaking change
=> Update telemetry resource attributes

CHANGELOG.md, specification/semantic_conventions.md
As I remember it was already deprecated as the `text` format is inefficient.
@gsmirnov-splk, could you please confirm?
=> Deprecate `text` format for `profiling.data.format`

.github/workflows/lychee-weekly.yml
Fixes: #288
Follows new recommendation how to execute weekly check:
https://github.com/lycheeverse/lychee-action/tree/c3089c702fbb949e3f7a8122be0c33c017904f9b#usage
Needed due to changes in 1.9.0 release: https://github.com/lycheeverse/lychee-action/pull/199
=> Create lychee GH issues only when action is failing

.github/workflows/cla.yml
https://github.com/cla-assistant org has been renamed to https://github.com/contributor-assistant.
=> Fix CLA GitHub Action after GH org rename

README.md, specification/repository.md
We have a need to make a public facing repo for cross-team o11y collaboration that it not necessarily otel-specific. So to help with that, this PR:
* Expands the "GDI repository" terminology to include repos starting with `o11y-` and existing in `repositories.txt`
* Include all of Cisco and AppD and Splunk as team members.
=> Relax repo name restrictions and include Cisco/AppD

specification/configuration.md
`OTLP_EXPORTER_OTLP_ENDPOINT` doesn't exist
=> Fix default value explanation for SPLUNK_PROFILER_LOGS_ENDPOINT

specification/behaviors.md
Fixes https://github.com/signalfx/gdi-specification/issues/323
=> Remove semantic convention from Call Stack Span Association

CHANGELOG.md, specification/behaviors.md, specification/configuration.md
Fixes #322 
The 1 second interval is currently used in our Node.js and Python distros. Java and .NET have 10 seconds.
The 10 second interval was meant for cases where threads might exist to limit the amount of data.
=> Update SPLUNK_PROFILER_CALL_STACK_INTERVAL default

CHANGELOG.md, specification/configuration.md
OpenTelemetry defaults to `parentbased_always_on`, but this is not consistent across our distributions:
* `parentbased_always_on` is used by Node.js, .NET, Python
* `always_on` is used by Java, [Go](https://github.com/signalfx/splunk-otel-go/blob/4b4f13d128bffd4035331cb84dc796a07b448803/distro/otel.go#L159)
If we are advertising as a no sampling solution, we should default to `always_on`, but still allow for customers to change it.
Using `parentbased_always_on` can cause data loss if customers have previously set up cloud tracing, which injects a `traceparent` with `00` for `traceflags`.
=> Clarify default sampler

README.md, specification/versioning.md
Call out that the versioning the GDI components should by also idiomatic to their language; examples:
- Python: https://packaging.python.org/en/latest/discussions/versioning/ (e.g. in SemVer it should be `v1.2.0-rc.1` and not `1.2.0rc1`)
- Go: https://go.dev/doc/modules/version-numbers (`v` prefix is not really SemVer compliant)
`README.md` defines the GDI **specification** versioning and status.
`VERSIONING.md` defines GDI **component** versioning requirements.
Fixes https://github.com/signalfx/gdi-specification/issues/327
=> Refactor versioning docs

Makefile
From https://cli.github.com/manual/gh_repo_clone
```
gh repo clone <repository> [<directory>] [-- <gitflags>...]
[...]
$ gh repo clone cli/cli -- --depth=1
```
=> chore: speedup releasing by cloning depth=1

specification/integration_context.md
Several people have brought up the point that putting the extra attributes on ALL spans with in a process shouldn't be necessary to paint the service map. Just the first one should suffice...so I'm hearing that feedback and applying it in this PR.
=> AppD context -- First span is all we need.
