signalfx/gdi-specification

specification/configuration.md
Given this has come up a few times and the specification may not always
be clear on expectations, make it explicit that installation and
configuration optimize for CX and TTV. Provide a concrete example to
help reinforce the point.
=> Optimize for CX and TTV

README.md, specification/semantic_conventions.md
Proposal: https://github.com/signalfx/gdi-specification/discussions/93
=> Document recommendations around semantic conventions

README.md, specification/configuration.md, specification/versioning.md
- Define and use `component` consistently
- Require experimental components to be opt-in
- Define component stability
=> Clarify experimental requirements

specification/repository.md
I'm not that convinced about `MUST NOT`, but let's start with stricter requirements and relax them if it's needed.
=> Change RELEASING.md requirements

CHANGELOG.md
- Update stability guarantee for all specification documents.
=> Release 1.0.0-rc.3

specification/templates/.github/CODEOWNERS
Fixes https://github.com/signalfx/gdi-specification/pull/115#discussion_r676356343
=> Add maintainers+approvers to docs CODEOWNERS

CHANGELOG.md, specification/configuration.md
=> Add support for the OTEL_SERVICE_NAME env var

specification/repository.md
=> repository - shared teams update

specification/repository.md, specification/templates/LICENSE
Fixes https://github.com/signalfx/gdi-specification/issues/127
=> Add LICENSE to templates

specification/configuration.md
Also update limit unset value to `""`
=> Add OTEL_ATTRIBUTE_VALUE_LENTH_LIMIT to spec

README.md, specification/versioning.md
Proposal to get Helm chart to 1.0
=> Add packaging specification information

CHANGELOG.md, specification/configuration.md, specification/semantic_conventions.md
- Mostly refactoring of existing language.
- Mark RUM and serverless experimental
=> Update instrumentation specification

specification/configuration.md
This is a remake of #150.
I thought it also made sense to make a default column, and the oddly centered content looked odd, so I just made it left aligned.
=> Add SPLUNK_PROFILER_CALL_STACK_INTERVAL

specification/configuration.md
Fix link changed by https://github.com/open-telemetry/opentelemetry-specification/pull/2479
Resolve #168
Resolve #169 
Resolve #170
=> Update link to OTel spec

.github/ISSUE_TEMPLATE/ga_request.md
- Fix hyperlinks to use the latest release - the current hyperlinks are not working; see: https://github.com/signalfx/gdi-specification/issues/173
- Fix indentation of the bullets
- Use headers instead of bolded lines as suggested by `markdownlint`
=> Fix GA request issue template

specification/repository.md
=> Clarify the out-of-the-box tools

specification/repository.md
I think it was the original intention.
@owais @flands PTAL
=> MUST NOT use GitHub secrets

specification/configuration.md
Based on the discussion in https://github.com/signalfx/gdi-specification/issues/190
=> Deprecate jaeger-thrift-splunk

specification/configuration.md
Towards https://github.com/signalfx/gdi-specification/issues/197
=> Clarify the policy regarding Zipkin exporter

specification/configuration.md
Gold-plating 😄 
Fixes https://github.com/signalfx/gdi-specification/issues/197
Why? Start reading from [here](https://github.com/signalfx/gdi-specification/issues/197#issuecomment-1313870766).
=> Remove Zipkin policy

specification/templates/CONTRIBUTING.md
Fixes https://github.com/signalfx/gdi-specification/issues/216
=> CONTRIBUTING.md - commits have to be signed

specification/repository.md
Lychee Link Checker is a GitHub Action. Not a GitHub App.
=> Move Lychee Link Checker to correct section

RELEASING.md
I think the new step can be manual as it would be anyway good to manually revise the GA request template.
=> Update GA request template after release

specification/semantic_conventions.md
=> Fix link after moving sem-conv to own repository

.github/workflows/cla.yml
See https://github.com/signalfx/splunk-otel-android/pull/661
@mateuszrzeszutek @laurit Sorry for the bug.
=> Fix CLA Assistant for dependabot

.github/ISSUE_TEMPLATE/ga_request.md, repositories.txt, specification/configuration.md, specification/repository.md, specification/semantic_conventions.md
This is no longer maintained within GDI.
=> Remove real user monitoring / rum
